# Generated by Django 5.2.5 on 2025-09-02 01:07

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_daerah', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=700)),
                ('image', models.ImageField(null=True, upload_to=basic.models.get_file_path)),
                ('slug', models.CharField(max_length=100)),
                ('tarian', models.CharField(blank=True, max_length=100, null=True)),
                ('baju_adat', models.CharField(blank=True, max_length=100, null=True)),
                ('alat_musik', models.CharField(blank=True, max_length=100, null=True)),
                ('link_ref', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
