# Generated by Django 5.2.5 on 2025-09-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupinfo',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Koordinat latitude titik pemancar', null=True),
        ),
        migrations.AddField(
            model_name='popupinfo',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Koordinat longitude titik pemancar', null=True),
        ),
    ]
